/*
 * LED_MATRIX_configuration.h
 *
 *  Created on: Feb 25, 2022
 *      Author: noureldeen albrmky
 */

#ifndef HAL_LED_MATRIX_LED_MATRIX_CONFIGURATION_H_
#define HAL_LED_MATRIX_LED_MATRIX_CONFIGURATION_H_

#define LMTRX_ROW1	GPIO_PORTA,0
#define LMTRX_ROW2	GPIO_PORTA,1
#define LMTRX_ROW3	GPIO_PORTA,2
#define LMTRX_ROW4	GPIO_PORTA,3
#define LMTRX_ROW5	GPIO_PORTA,4
#define LMTRX_ROW6	GPIO_PORTA,5
#define LMTRX_ROW7	GPIO_PORTA,6
#define LMTRX_ROW8	GPIO_PORTA,7

#define LMTRX_COL1	GPIO_PORTA,8
#define LMTRX_COL2	GPIO_PORTA,9
#define LMTRX_COL3	GPIO_PORTA,10
#define LMTRX_COL4	GPIO_PORTA,11
#define LMTRX_COL5	GPIO_PORTA,12
#define LMTRX_COL6	GPIO_PORTC,13
#define LMTRX_COL7	GPIO_PORTC,14
#define LMTRX_COL8	GPIO_PORTC,15

#endif /* HAL_LED_MATRIX_LED_MATRIX_CONFIGURATION_H_ */
